version: '3.8'

services:
  pdf-generator:
    build: 
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    image: pdf-generator:latest
    container_name: pdf-generator
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # 安全设置
    security_opt:
      - no-new-privileges:true
    # 共享内存设置
    shm_size: 2gb
    networks:
      - pdf-network

networks:
  pdf-network:
    driver: bridge